# Generated by Django 5.0.1 on 2025-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.IntegerField(help_text='Delivery location latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.IntegerField(help_text='Delivery location longitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_latitude',
            field=models.IntegerField(help_text='Pickup location latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_longitude',
            field=models.IntegerField(help_text='Pickup location longitude'),
        ),
    ]
