# Generated by Django 5.0.1 on 2025-03-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_deliver_payment_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_payment_by',
            field=models.CharField(choices=[('user', 'Paid by User'), ('customer', 'Paid by Customer')], default='user', help_text='Who will pay the product price', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.FloatField(help_text='Delivery location latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.FloatField(help_text='Delivery location longitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_latitude',
            field=models.FloatField(help_text='Pickup location latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_longitude',
            field=models.FloatField(help_text='Pickup location longitude'),
        ),
    ]
