# Generated by Django 5.0.1 on 2025-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_deliver_payment_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(default='11111.jpg', help_text='Optional image for the order', upload_to='order_images/'),
            preserve_default=False,
        ),
    ]
