# Generated by Django 5.0.1 on 2025-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(help_text='Optional image for the order', max_length=100),
        ),
    ]
