# Generated by Django 5.0.1 on 2025-03-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_payment_by',
            field=models.CharField(choices=[('user', 'Paid by User'), ('customer', 'Paid by Customer')], help_text='Who will pay the product price', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_by',
            field=models.CharField(choices=[('user', 'Paid by User'), ('courier', 'Paid by Courier')], help_text='Who will pay the delivery price', max_length=10),
        ),
    ]
