# Generated by Django 5.0.1 on 2025-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
