# Generated by Django 5.0.1 on 2025-04-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_address_order_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='map',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
