# Generated by Django 5.0.1 on 2025-04-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='map',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(null=True),
        ),
    ]
